version: "3"
services:
  app_golang:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_golang
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/app
    # ports:
      # - "7010:8080"
    working_dir: /app
    network_mode: "host"   
    extra_hosts:
      - "host.docker.internal:host-gateway"



