version: "3"
services:
  app_golang:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_golang
    restart: unless-stopped
    tty: true
    ports:
      - "7010:8080"
    working_dir: /app
    networks:
      - dev
    extra_hosts:
      - "host.docker.internal:host-gateway"


networks:
  dev:

